# Generated by Django 5.2.8 on 2025-11-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
