# Generated by Django 5.2.8 on 2025-11-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customer_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="address",
        ),
    ]
