# Generated by Django 5.2.8 on 2025-11-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_customer_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseimage",
            name="predicted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="houseimage",
            name="predicted_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
