# Generated by Django 6.0.1 on 2026-02-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_houseimage_predicted_at_houseimage_predicted_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="damage_types",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="roof_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="house",
            name="severity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
