# Generated by Django 6.0.1 on 2026-02-11 19:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_house_damage_types_house_roof_type_house_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                default="johndoe@example.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, default="+123-456-7890", max_length=128, region=None
            ),
        ),
    ]
