# Generated by Django 6.0.1 on 2026-02-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customer_email_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseimage",
            name="detections",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
