# Generated by Django 6.0.1 on 2026-02-11 20:14

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_houseimage_detections_alter_house_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="+123-456-7890",
                max_length=128,
                region=None,
                unique=True,
            ),
        ),
    ]
