# Generated by Django 6.0.1 on 2026-02-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="price_estimate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
