# Generated by Django 6.0.1 on 2026-02-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="default_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
