# Generated by Django 6.0.1 on 2026-02-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_house_default_image"),
        ("core", "0009_house_price_estimate"),
    ]

    operations = []
